#pragma once

#define MAIN_WINDOW_NAME "FSI Data Collection Tool"
#define DCV_WINDOW_NAME "Data Collection Viewer"
#define MAX_FRAME_RATE 15
#define MIN_FRAME_LENGTH_MS (1000 / MAX_FRAME_RATE)

#define SMALL_BURST_SIZE 10
#define LARGE_BURST_SIZE 20
#define CLIP_LENGTH 8
#define NUM_SAMPLES_PER_CAPTURE 12
#define NUM_CAPTURES_PER_LETTER 50
#define NUM_SAMPLES_PER_LETTER (NUM_SAMPLES_PER_CAPTURE * NUM_CAPTURES_PER_LETTER)
#define NUM_LETTERS 25
#define BEEP_COUNT 4

#define HAAR_MODEL_FILENAME "aHand.xml"
#define DATA_RAW_FILENAME "data.raw"
#define LABEL_RAW_FILENAME "labels.raw"
#define CLIP_DATA_RAW_FILENAME "clipData.raw"
#define CLIP_LABEL_RAW_FILENAME "clipLabels.raw"
#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480
#define IMAGE_SIZE 80
#define CLIP_IMAGE_SIZE 64
#define NUM_SPLIT_FILES 4

#define BOUND_LOOSE_FACTOR 2.5
#define BOUND_LOOSE_OFFSET ((BOUND_LOOSE_FACTOR - 1.0) * 0.5)
#define BOUND_TIGHT_FACTOR 0.35
#define BOUND_TIGHT_OFFSET ((1.0 - BOUND_TIGHT_FACTOR) * 0.5)
#define BOUND_FOCUS_FACTOR 0.9
#define BOUND_FOCUS_OFFSET ((1.0 - BOUND_FOCUS_FACTOR) * 0.5)
#define TIGHT_AREA (BOUND_TIGHT_FACTOR * BOUND_TIGHT_FACTOR)
#define MAX_OUTLIER_FACTOR 6.0

#define MATH_PI 3.14159265358979f

enum eBoundType { BOUND_LOOSE, BOUND_TIGHT, BOUND_FOCUS };
